[package]
edition = "2021"
name = "dendro-parse"
version = "0.1.0"

[dependencies]
# Local crates
dendro-ast = {path = "../ast"}
dendro-lexer = {path = "../lexer"}
dendro-span = {path = "../span"}
# External crates
pest = "2.7"
