[package]
edition = "2021"
name = "dendro-resolve"
version = "0.1.0"

[dependencies]
# Local crates
dendro-ast = {path = "../ast"}
dendro-error = {path = "../error"}
dendro-expand = {path = "../expand"}
dendro-span = {path = "../span"}
