[package]
edition = "2021"
name = "dendro-lexer"
version = "0.1.0"

[dependencies]
# Local crates
dendro-ast = {path = "../ast"}
dendro-error = {path = "../error"}
dendro-span = {path = "../span"}
# External crates
pest = "2.7"
pest_derive = "2.7"
