[package]
edition = "2021"
name = "dendro-expand"
version = "0.1.0"

[dependencies]
# Local crates
dendro-ast = {path = "../ast"}
dendro-error = {path = "../error"}
dendro-lexer = {path = "../lexer"}
dendro-parse = {path = "../parse"}
dendro-span = {path = "../span"}
